### ISSUE TITLE
incorporating CollectRnaSeqMetrics output in report

### ISSUE THREAD

**Issue by MSaadfarooq** [MultiQC/MultiQC#2608]
### Description of bug

when used multiqc, all other qc reports incorporated to multiqc report exept picard's CollectRnaSeqMetrics output files. one of these files attached along with log files.

### File that triggers the error

[multiqc_data.zip](https://github.com/user-attachments/files/15578795/multiqc_data.zip)

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this issue! It was indeed broken in MultiQC v1.22. It's addressed with https://github.com/MultiQC/MultiQC/pull/2609 now, will be a part of a patch release, or feel free to use the dev code base from the main branch of the repo!

**Comment by vladsavelyev** [comment]
Fixed with https://github.com/MultiQC/MultiQC/pull/2610, will release a patch release soon.

**Comment by Lucpen** [comment]
Hi, I have tried using the latest version, 1.24.1, but I am still having the same issue. Is there anything I should check from my side?

**Comment by joelsoo** [comment]
> Fix a search pattern of Picard CollectRnaSeqMetrics #2811

Same here, having issues with the v1.24.1

**Comment by vladsavelyev** [comment]
@Lucpen and @joelsoo, would you be able to share the Picard output that MultiCC doesn't pick up? The one that the topic starter attached works for me, as well as all test examples we have in test-data/data/modules/picard/RnaSeqMetrics. Would be amazing to collect more test cases to support various formats that Picard or Picard-based tools output.
