### ISSUE TITLE
run_modules in configuration suppresses usage of *_mqc_versions.yml files

### ISSUE THREAD

**Issue by pinin4fjords** [MultiQC/MultiQC#2750]
### Description of bug

With 1.21, running multiqc within a directory like the attached recognises the *_mqc_versions.yml

[test_versions.tar.gz](https://github.com/user-attachments/files/16561048/test_versions.tar.gz)

... and you get HTML content like this:

[multiqc_report.html.zip](https://github.com/user-attachments/files/16561217/multiqc_report.html.zip)

... as per [the documentation](https://multiqc.info/docs/reports/customisation/#software-versions-yaml-file).

with 1.22 and 1.23, the file seems to be ignored.

### File that triggers the error

[test_versions.zip](https://github.com/user-attachments/files/16561241/test_versions.zip)

### MultiQC Error log

```console
$ rm -rf multiqc_report.html multiqc_data &&  multiqc .

/// MultiQC 🔍 v1.22.2

     version_check | MultiQC Version v1.23 now available!
       file_search | Search path: /Users/jonathan.manning/Downloads/test_multiqc
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
      exec_modules | No analysis results found. Cleaning up…
      exec_modules | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
It needs some data besides the versions. Does it ignore versions if you have some other modules as well?

**Comment by pinin4fjords** [comment]
> It needs some data besides the versions. Does it ignore versions if you have some other modules as well?

Yes, that was the scenario in which I originally identified the issue (in nf-core/rnaseq). I'll double-check with something smaller

**Comment by pinin4fjords** [comment]
Same deal even if you supply data as well:

[test_versions.zip](https://github.com/user-attachments/files/16563856/test_versions.zip)

**Comment by vladsavelyev** [comment]
Ah, you must be using 1.22. It was fixed in 1.23. Sorry about this!

**Comment by pinin4fjords** [comment]
> Ah, you must be using 1.22. It was fixed in 1.23. Sorry about this!

You're right, that does work with 1.23, but 1.23 does not work in the larger rnaseq context, where the versions still get lost. I'll try to figure out the conditions that do that and come back to you.

**Comment by pinin4fjords** [comment]
OK, got it, it's this configuration:

```
run_modules:
  - custom_content
  - fastqc
  - cutadapt
  - fastp
  - sortmerna
  - star
  - hisat2
  - rsem
  - umitools
  - salmon
  - kallisto
  - samtools
  - picard
  - preseq
  - rseqc
  - qualimap
```

Stripping this from the config in rnaseq causes the versions to re-appear in the reports. In the case of the minimal example, adding a configuration like this suppresses the versions. 

[test_versions.zip](https://github.com/user-attachments/files/16564573/test_versions.zip)

I can't see a module I can explicitly enable to take note of the software versions, but let me know if there is one. Otherwise I guess there's a conditional wrong somewhere.

**Comment by vladsavelyev** [comment]
Oh, I see. When `run_modules ` is set explicitly, MultiQC only executes the modules listed, so the `software_versions` special-case "module" will note run here. But adding it to the list also won't work because it's special-case 😬 . Fixed MultiQC now to always included software_versions: https://github.com/MultiQC/MultiQC/pull/2755

**Comment by pinin4fjords** [comment]
Thanks @vladsavelyev ! Thought it might be something like that.
