### ISSUE TITLE
Kraken not being added to multiqc report after going from 1.23 to 1.24.1

### ISSUE THREAD

**Issue by nschcolnicov** [MultiQC/MultiQC#2801]
### Description of bug

Im currently updating the MultiQC module on nf-core/demultiplex, but I saw that the version 1.24.1 doesn't add this section anymore. I didn't change anything else besides the container.

Original MultiQC with version 1.23 (quay.io/biocontainers/multiqc:1.23--pyhdfd78af_0) report looks like this:
![image](https://github.com/user-attachments/assets/dbe8da61-d3cf-4b6c-823e-1d1cb2d59570)
While running the same with version 1.24.1 (quay.io/biocontainers/multiqc:1.24.1--pyhdfd78af_0) it looks like this (**it is missing, but you can see that kraken ran)**:
![image](https://github.com/user-attachments/assets/0d7152f6-7000-43ee-8497-21ce3fc52302)

These reports were obtained from running the nf-tests from nf-core/demultiplex, latest dev branch.

Commands to reproduce:
Running old multiqc version, uses container **quay.io/biocontainers/multiqc:1.23--pyhdfd78af_0**:
```
git clone https://github.com/nf-core/demultiplex.git
cd demultiplex
git checkout dev
nf-test test tests/pipeline/kraken.nf.test --profile +docker
```
Run these same commands after updating the MultiQC module to use container **quay.io/biocontainers/multiqc:1.24.1--pyhdfd78af_0** and look at the MultiQC report generated.

I can't share the MultiQC reports here, but the only difference that I found was that one has the kraken section and the other one doesnt.

Additional info:
Inside the multiqc_data folder I see a file being outputed labeled "kraken-top-n-plot.txt" for the 1.23 version, which contains this:
```
Sample	Unclassified
Sample1_S1_L001	100000
```
While for version 1.24.1 I see a file labeled "multiqc_kraken.txt" which contains this:
```
Sample	U	R
Sample1_S1_L001	{'unclassified': 100000}	{'root': 0}
 ```

### File that triggers the error

Workdir from nextflow with all of the files and commands required to trigger the error:
[workdir.tar.gz](https://github.com/user-attachments/files/16788447/workdir.tar.gz)

### MultiQC Error log

```console
Unable to find image 'quay.io/biocontainers/multiqc:1.24.1--pyhdfd78af_0' locally
1.24.1--pyhdfd78af_0: Pulling from biocontainers/multiqc
36b7914fc8ba: Pulling fs layer
2cc3d3b08aaa: Pulling fs layer
bd9ddc54bea9: Pulling fs layer
7308f92292bf: Pulling fs layer
7308f92292bf: Waiting
bd9ddc54bea9: Download complete
2cc3d3b08aaa: Verifying Checksum
2cc3d3b08aaa: Download complete
36b7914fc8ba: Verifying Checksum
36b7914fc8ba: Download complete
7308f92292bf: Verifying Checksum
7308f92292bf: Download complete
36b7914fc8ba: Pull complete
2cc3d3b08aaa: Pull complete
bd9ddc54bea9: Pull complete
7308f92292bf: Pull complete
Digest: sha256:0e80f2cbbfece8a52c7ad645a751b1d34465a4053904c5130b3a7a81ac5e02f6
Status: Downloaded newer image for quay.io/biocontainers/multiqc:1.24.1--pyhdfd78af_0

/// MultiQC 🔍 v1.24.1

            config | Loading config settings from: multiqc_config.yml
            config | Loading config settings from: multiqc_config.yml
       file_search | Search path: /workspace/demultiplex/.nf-test/tests/de4760fccc143099e9ca653fac31a64a/work/c2/b3af61cdc223405ad39e1bd39fdecf

            fastqc | Found 1 reports
             fastp | Found 1 reports
    custom_content | nf-core-demultiplex-summary: Found 1 sample (html)
    custom_content | nf-core-demultiplex-methods-description: Found 1 sample (html)
            kraken | Found 1 reports
╭───────────────── Oops! The 'kraken' MultiQC module broke... ─────────────────╮
│ Please copy this log and report it at                                        │
│ https://github.com/MultiQC/MultiQC/issues                                    │
│ Please attach a file that triggers the error. The last file found was:       │
│ 8/Sample1_S1_L001.kraken2.report.txt                                         │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/core/exec_modules.py │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = modul │
│                                                                        ^^^^^ │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/kraken/krake │
│     self.top_taxa_barplot(total_cnt_by_sample, pct_by_top_taxon_by_rank, cnt │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/kraken/krake │
│     plot=bargraph.plot(rank_datasets, cats, pconfig),                        │
│          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                         │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/bargraph.py",  │
│     elif isinstance(cats, List) and isinstance(cats[0], str):                │
│                                                ~~~~^^^                       │
│ IndexError: list index out of range                                          │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
     write_results | Plots       : multiqc_plots
           multiqc | MultiQC complete















/// MultiQC 🔍 v1.23

            config | Loading config settings from: multiqc_config.yml
     version_check | MultiQC Version v1.24.1 now available!
       file_search | Search path: /demultiplex/.nf-test/tests/f49b449eaffb5353dadc2b7af878860f/work/b5/b3ce785f4fd14561f26bb80d49654c

            fastqc | Found 1 reports
             fastp | Found 1 reports
    custom_content | nf-core-demultiplex-summary: Found 1 sample (html)
    custom_content | nf-core-demultiplex-methods-description: Found 1 sample (html)
            kraken | Found 1 reports

     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
     write_results | Plots       : multiqc_plots
           multiqc | MultiQC complete




Report file used as input: Sample1_S1_L0001.kraken2.report.txt
100.00	100000	100000	U	0	unclassified
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by vladsavelyev** [comment]
Sorry about this issue! I wonder if you could share the `8/Sample1_S1_L001.kraken2.report.txt` file from the work dir? The archive you attached unfortunately only contains symlinks.

**Comment by vladsavelyev** [comment]
But from what I can guess, the module didn't handle the edge-case properly when no reads were classified to any taxa. This should fix it: https://github.com/MultiQC/MultiQC/pull/2822

**Comment by nschcolnicov** [comment]
Hi @vladsavelyev Thank you for looking into this, although the new version fixed the error that was being raised, MultiQC report still doesn't display the kraken plot. I created a new issue for this: https://github.com/MultiQC/MultiQC/issues/2876
